### PR TITLE
Rob Morgan - Mod4 - Prework

### PR DESCRIPTION
**Pull request by rmorgan323**
Add node server tutorial link
Add express tutorial link
Add promise practice exercises link

### CODE REVIEW

**Comment by rmorgan323** [comment]
Submit Palette Picker project - Rob Morgan - Mod 4 FE

**Comment by rmorgan323** [comment]
Update HomeworkSubmissions for Rob Morgan
Add link to Heroku for palette-picker-pwa

**Comment by rmorgan323** [comment]
Update submissions template for Rob Morgan - 1708FE
Add Pattrn Party repo link
Add Pattrn Party site link

**Comment by robbiejaeger** [comment]
@rmorgan323 Looks like you just edited the submission template in for your palette picker submission. Make a new copy of the submission template with your name in the filename, and then update the PR. Thanks!

**Pull request merged**
