### PR TITLE
Update homework-submissions.md

### PR DESCRIPTION
**Pull request by airum82**

### CODE REVIEW

**Comment by airum82** [comment]
It has been revised

**Comment by robbiejaeger** [comment]
@airum82 This is still not the assignment from the prework for Promises. We need you to complete these exercises:

https://gist.github.com/robbiejaeger/dc8f55c1f9462741090862f736b82cab#promise-approach-on-your-own

**Comment by airum82** [comment]
Sorry I was confused on the exercise, I have rewrote it to match the actual exercises.

**Comment by robbiejaeger** [comment]
@airum82 No worries, thanks for the update.

**Pull request merged**
